import type { RouteSummary } from '../api';

/**
 * View-model types for the route planner (M2-03 territory).
 *
 * The schedule, slot, competition and performance surfaces have **no server
 * endpoints yet** — the route and fare endpoints are real, everything else here is
 * generated by `planner/mock.ts`. These types deliberately mirror the shapes a
 * future backend would return (see `@tailfin/shared`'s `Schedule`, `ScheduleLeg`,
 * `RepeatPattern`) so wiring the real data in later is a swap of the data source,
 * not a rewrite of the components.
 */

/** ISO weekday, 1 = Monday … 7 = Sunday, matching `@tailfin/shared`'s `IsoWeekday`. */
export type Weekday = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const WEEKDAYS: readonly Weekday[] = [1, 2, 3, 4, 5, 6, 7];
export const WEEKDAY_LABEL: Record<Weekday, string> = {
  1: 'Mon',
  2: 'Tue',
  3: 'Wed',
  4: 'Thu',
  5: 'Fri',
  6: 'Sat',
  7: 'Sun',
};

/** How often a rotation runs — the client mirror of `RepeatPattern`. */
export type Frequency = { kind: 'daily' } | { kind: 'weekdays'; days: Weekday[] };

/** One aircraft the planner can lay flights against — a real airframe or the pool. */
export interface PlannerAircraft {
  /** `airframeId` for a real aircraft; `'pool'` for the unassigned fleet pool. */
  id: string;
  registration: string;
  typeDesignation: string;
  aircraftClass: string;
  /** Block hours a day this aircraft is already working, for the utilisation bar. */
  utilisationHoursPerDay: number;
  /** True for the synthetic fleet-pool row rather than a real airframe. */
  isPool: boolean;
}

/** A flight laid on the timeline — one leg of a rotation on one aircraft. */
export interface PlannedFlight {
  id: string;
  aircraftId: string;
  routeId: string;
  originIcao: string;
  destinationIcao: string;
  /** Minutes from local midnight. */
  departureMinute: number;
  /** Block time in minutes (taxi + air time), so arrival is dep + block. */
  blockMinutes: number;
  /** Which way round the rotation this leg flies, for the label arrow. */
  direction: 'out' | 'back';
  frequency: Frequency;
}

/** A departure band's slot — its price, how good the time is, and whether it is free. */
export interface Timeslot {
  /** Hour of the local day, 0–23. */
  hour: number;
  quality: 'peak' | 'shoulder' | 'offpeak';
  availability: 'available' | 'limited' | 'full';
  /** Slot cost in minor units, per departure. */
  costMinor: number;
}

/** A rival on the route, for the Competition tab and context panel. */
export interface Competitor {
  id: string;
  name: string;
  /** Weekly frequency they fly. */
  weeklyFrequency: number;
  /** Their headline economy fare, minor units. */
  economyFareMinor: number;
  /** Their projected share of the market, 0–1. */
  share: number;
  /** A coarse product tier, for the little bar. */
  product: 'basic' | 'standard' | 'premium';
}

/** Daily demand split, for the Overview and Competition tabs. */
export interface DemandBreakdown {
  business: number;
  leisure: number;
  vfr: number;
}

/** Rolled-up route economics for the Overview tab. */
export interface RouteEconomics {
  weeklyFrequency: number;
  loadFactor: number;
  /** Revenue and cost per available seat kilometre, minor units. */
  raskMinor: number;
  caskMinor: number;
  weeklyRevenueMinor: number;
  weeklyCostMinor: number;
  /** Average block hours a day across the aircraft on this route. */
  utilisationHoursPerDay: number;
}

/** A whole route's mock plan, everything the tabs read. */
export interface RoutePlan {
  route: RouteSummary;
  frequency: Frequency;
  flights: PlannedFlight[];
  slots: Timeslot[];
  competitors: Competitor[];
  demand: DemandBreakdown;
  economics: RouteEconomics;
  /** A 12-point weekly load-factor trend, 0–1, for the Performance sparkline. */
  loadTrend: number[];
}

/** What the context panel is currently describing on the Network page. */
export type NetworkSelection =
  | { kind: 'route'; id: string }
  | { kind: 'flight'; id: string }
  | { kind: 'aircraft'; id: string }
  | { kind: 'slot'; id: string };
