/**
 * Where an aircraft is, and what it costs to be somewhere else (M2-07, §7.2).
 *
 * An aircraft is a physical object at a place. That sounds too obvious to model,
 * and it is exactly the assumption a schedule editor lets a player break: a
 * rotation that starts at Heathrow, saved for an aircraft sitting in Amsterdam,
 * is a rotation that teleports. §24's gap list names *"aircraft delivery
 * positioning and ferry flights"* among the things the design doc does not
 * specify, so what follows is M2-07 deciding it.
 *
 * ## Position is derived, never stored
 *
 * There is no `location` column and there should not be one. An aircraft is
 * wherever its last completed movement left it, and that is a fold over flights
 * the database already holds. A stored column would be a second source of truth
 * that drifts the first time a flight is cancelled, diverted or replayed — and
 * §21 already settled this argument for flight state: *"computed, not stored per
 * tick"*. The same reasoning applies to the aircraft underneath it.
 *
 * The one thing that cannot be derived is where the aircraft **entered the
 * world**. A delivery has no previous flight, so the position it arrives at is
 * part of the order (M4-04), and it is the seed this fold starts from.
 *
 * ## A diversion moves the aircraft
 *
 * This is the case that makes derivation worth it rather than merely tidy. A
 * flight planned Amsterdam→Heathrow that diverts to Gatwick leaves the aircraft
 * **at Gatwick**, and tomorrow's rotation out of Heathrow is now impossible. A
 * stored position updated on arrival would have to remember to handle that; a
 * fold that reads where the aircraft actually went cannot get it wrong.
 */

/**
 * One completed movement, as thin as it can be.
 *
 * Deliberately not `Flight`: this module has no business knowing about phases,
 * loads or revenue, and taking the whole row would tie the fleet model to the
 * shape of a database table. What it needs is where the aircraft went.
 */
export interface Movement {
  originIcao: string;
  destinationIcao: string;
  /**
   * Where it actually ended up, when that is not where it was aimed (§8.4).
   *
   * Null for the ordinary case. When set it **wins** — the aircraft is where it
   * landed, not where the plan said.
   */
  diversionIcao?: string | null;
}

/** Where a movement left the aircraft. */
export function movementEndsAt(movement: Movement): string {
  return movement.diversionIcao ?? movement.destinationIcao;
}

/**
 * Where the aircraft is now.
 *
 * `movements` must be in the order they happened; the caller owns that ordering
 * because only it knows whether it is reading actual arrivals or a plan. The
 * fold does not check continuity — a gap between one arrival and the next
 * departure is exactly the bug this module exists to *report*, not to hide, and
 * {@link findPositioningGap} is what reports it.
 */
export function airframeLocation(deliveredTo: string, movements: readonly Movement[]): string {
  let at = deliveredTo;
  for (const movement of movements) {
    at = movementEndsAt(movement);
  }
  return at;
}

/** A movement that cannot happen, because the aircraft is somewhere else. */
export interface PositioningGap {
  /** Index in the movements given. */
  index: number;
  /** Where the aircraft actually is. */
  at: string;
  /** Where the movement expects it to be. */
  expected: string;
}

/**
 * The first movement that departs from somewhere the aircraft is not.
 *
 * Returns the *first* rather than all of them on purpose: once the sequence has
 * broken, every position after it is derived from a premise that is already
 * false, so a list of downstream complaints would be noise generated by the
 * first one. Fix that, re-check, and the rest either resolve or are real.
 */
export function findPositioningGap(
  deliveredTo: string,
  movements: readonly Movement[],
): PositioningGap | null {
  let at = deliveredTo;
  for (const [index, movement] of movements.entries()) {
    if (movement.originIcao !== at) {
      return { index, at, expected: movement.originIcao };
    }
    at = movementEndsAt(movement);
  }
  return null;
}

/**
 * The ferry needed to make a departure possible, or null if none is.
 *
 * The point of the whole module: an aircraft in the wrong place is not an error
 * to be refused, it is a **cost to be paid**. §18's event model says so directly
 * — *"event spikes cost real repositioning: ferry flights, crew hotelling"* — so
 * the useful answer to "this rotation cannot start here" is not "no" but "not
 * until you fly it there, and here is the leg that does it".
 */
export function ferryRequired(
  at: string,
  departingFrom: string,
): { originIcao: string; destinationIcao: string } | null {
  return at === departingFrom ? null : { originIcao: at, destinationIcao: departingFrom };
}
