import { describe, expect, it } from 'vitest';

import {
  airframeLocation,
  ferryRequired,
  findPositioningGap,
  type Movement,
  movementEndsAt,
} from './positioning';

/**
 * Where an aircraft is (M2-07, §7.2).
 *
 * Two claims carry the module, and the second is the one that makes deriving
 * position worth the trouble rather than merely tidy:
 *
 *   1. An aircraft is wherever its last movement left it.
 *   2. **A diversion counts.** A flight planned to Heathrow that lands at Gatwick
 *      leaves the aircraft at Gatwick, and tomorrow's rotation out of Heathrow is
 *      now impossible. A stored column would have to remember that; a fold over
 *      what actually happened cannot forget it.
 */

function leg(originIcao: string, destinationIcao: string, diversionIcao?: string): Movement {
  return { originIcao, destinationIcao, diversionIcao: diversionIcao ?? null };
}

describe('movementEndsAt', () => {
  it('is the destination for an ordinary flight', () => {
    expect(movementEndsAt(leg('EHAM', 'EGLL'))).toBe('EGLL');
  });

  it('is the diversion when there was one — that is where the aeroplane is', () => {
    expect(movementEndsAt(leg('EHAM', 'EGLL', 'EGKK'))).toBe('EGKK');
  });
});

describe('airframeLocation', () => {
  it('is the delivery airport before anything has been flown', () => {
    // M4-04's order says where a new aircraft turns up. Nothing else can.
    expect(airframeLocation('EHAM', [])).toBe('EHAM');
  });

  it('follows a day of flying to where it ends', () => {
    expect(
      airframeLocation('EHAM', [leg('EHAM', 'EGLL'), leg('EGLL', 'EHAM'), leg('EHAM', 'LFPG')]),
    ).toBe('LFPG');
  });

  it('ends where a rotation that closes began', () => {
    expect(airframeLocation('EHAM', [leg('EHAM', 'EGLL'), leg('EGLL', 'EHAM')])).toBe('EHAM');
  });

  it('follows a diversion rather than the plan', () => {
    expect(airframeLocation('EHAM', [leg('EHAM', 'EGLL', 'EGKK')])).toBe('EGKK');
  });

  it('carries a diversion forward — the next leg starts from where it landed', () => {
    // The compounding case, and the reason this is a fold rather than a lookup
    // of the last flight's destination.
    const after = airframeLocation('EHAM', [leg('EHAM', 'EGLL', 'EGKK'), leg('EGKK', 'EHAM')]);

    expect(after).toBe('EHAM');
  });
});

describe('findPositioningGap', () => {
  it('finds nothing when every leg starts where the last one ended', () => {
    expect(
      findPositioningGap('EHAM', [leg('EHAM', 'EGLL'), leg('EGLL', 'LFPG'), leg('LFPG', 'EHAM')]),
    ).toBeNull();
  });

  it('catches a first leg departing somewhere the aircraft is not', () => {
    // The teleportation M2-07 exists to refuse: aircraft in Amsterdam, schedule
    // starting at Heathrow.
    expect(findPositioningGap('EHAM', [leg('EGLL', 'LFPG')])).toEqual({
      index: 0,
      at: 'EHAM',
      expected: 'EGLL',
    });
  });

  it('catches a gap in the middle, and names which leg', () => {
    expect(findPositioningGap('EHAM', [leg('EHAM', 'EGLL'), leg('LFPG', 'EHAM')])).toEqual({
      index: 1,
      at: 'EGLL',
      expected: 'LFPG',
    });
  });

  it('treats a diversion as the new truth, so the next leg is the one at fault', () => {
    // The aircraft went to Gatwick. A leg out of Heathrow is now the broken one,
    // even though it was perfectly valid when the schedule was written.
    expect(findPositioningGap('EHAM', [leg('EHAM', 'EGLL', 'EGKK'), leg('EGLL', 'EHAM')])).toEqual({
      index: 1,
      at: 'EGKK',
      expected: 'EGLL',
    });
  });

  it('reports only the first gap, not every consequence of it', () => {
    // Once the sequence has broken, every position after it is derived from a
    // premise that is already false. A list of downstream complaints would be
    // noise generated by the first one.
    const gap = findPositioningGap('EHAM', [
      leg('LFPG', 'EGLL'),
      leg('EDDF', 'EHAM'),
      leg('LEMD', 'EGLL'),
    ]);

    expect(gap?.index).toBe(0);
  });
});

describe('ferryRequired', () => {
  it('is nothing when the aircraft is already there', () => {
    expect(ferryRequired('EHAM', 'EHAM')).toBeNull();
  });

  it('is the leg that closes the gap', () => {
    // The answer a schedule editor wants: not "no", but "not until you fly it
    // there, and here is the leg that does it" (§18's repositioning cost).
    expect(ferryRequired('EHAM', 'EGLL')).toEqual({
      originIcao: 'EHAM',
      destinationIcao: 'EGLL',
    });
  });
});
